# User blueprints are used to create new user roles, define form fields for each user role and set role permissions.
# By default, Kirby only has the `admin` role, a user role that is allowed to do anything.
# The title is required, everything else is optional.
# The default user blueprint does not define a role, but a standard set of fields
# available for each defined user role with blueprints that only contain a title.
# More about users, roles and permissions: https://getkirby.com/docs/guide/users/managing-users
title: User

columns:
  - width: 1/2
    fields:
      website:
        label: Website
        type: url
      linkedin:
        label: LinkedIn Profile
        type: url
        placeholder: https://www.linkedin.com/in/<username>/
      bio-short:
        label: Bio (kurz)
        type: textarea
        buttons: false
        counter: true
        size: small

  - width: 1/2
    fields:
      fediverse:
        label: Fediverse URL
        type: url
        icon: mastodon
        placeholder: https://example.com/@username
      instagram:
        label: Instagram
        type: text
        icon: instagram
        placeholder: username